### ISSUE TITLE
有没有如何导入得教程呢

### ISSUE THREAD

**Issue by Anymre** [Tiakon/gitiakon#5]
用eclipse导入有很多错误，可以回复一下吗

**Comment by Tiakon** [comment]
> 用eclipse导入有很多错误，可以回复一下吗

你好，最新版的重构还没有完成，请下载1.5版本的再到入

**Comment by Tiakon** [comment]
> 用eclipse导入有很多错误，可以回复一下吗
你好最新2.0版的重构没有完成，请下载1.5版。
![image](https://user-images.githubusercontent.com/21116907/47280356-99031a80-d608-11e8-874d-a7e1714df05b.png)
